default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: jose
  password: 'JOSE200310'
  database: open_flights
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

production:
  <<: *default
